'use client'
import { ReactNode } from 'react'
import './globals.css'
import { Nunito } from 'next/font/google'
import { Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: ReactNode
  session: Session | null
}

export default function RootLayout({ children, session }: LayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} box-border min-h-screen max-w-[calc(100vw-1.25rem)] bg-gray-800 p-5 text-gray-200`}
      >
        <SessionProvider session={session}>
          <div className="flex min-h-[calc(100vh-2.5rem)] w-full">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
